name: Chromium Pester experiment

trigger:
  branches:
    include:
      - refs/tags/*

pr:
  branches:
    include:
      - master

jobs:
  - job: Main
    pool:
      vmImage: VS2017-Win2016
    steps:
      - task: Bash@3
        displayName: Install browser runtime dependencies
        inputs:
          targetType: inline
          script: npm install
          workingDirectory: ./browser-scenario
      - task: PowerShell@2
        displayName: Run tests
        inputs:
          targetType: inline
          script: |
            Install-Module Pester -Force -Scope CurrentUser;
            Invoke-Pester @{Path= '$(Build.SourcesDirectory)/*.tests.ps1'; Parameters = @{AgentTempDirectory='$(Agent.TempDirectory)'}}
