name: Chromium Pester experiment

trigger:
  branches:
    include:
      - refs/tags/*

pr:
  branches:
    include:
      - master

jobs:
  - job: Main
    pool:
      vmImage: VS2017-Win2016
    steps:
      - task: Bash@3
        displayName: Install browser instrumentation
        inputs:
          targetType: inline
          script: npm install
          workingDirectory: ./browser-scenario

      - powershell: Install-Module Pester -Force -Scope CurrentUser
        displayName: Install Pester
        
      - powershell: Invoke-Pester @{Path= '$(Build.SourcesDirectory)/*.tests.ps1'; Parameters = @{AgentTempDirectory='$(Agent.TempDirectory)'}}
        displayName: Run tests
